### ISSUE TITLE
image_editor_pro depends on permission_handler ^4.2.0+hotfix.3 and myapp depends on permission_handler ^5.0.0+hotfix.3

### ISSUE THREAD

**Issue by gisinator** [zeeshux7860/ImageEditorPro#3]
Hi,

first of all: Appreciate the time and effort you put into this plugin. Your description sounds like exactly what I am looking for, so thank you very much.

When trying to install though, I get the following error: 

Because every version of image_editor_pro depends on permission_handler ^4.2.0+hotfix.3 and myApp depends on permission_handler ^5.0.0+hotfix.3, image_editor_pro is forbidden.

So, because myApp depends on image_editor_pro ^1.0.5, version solving failed.

Any chance you can fix this so that it can be used with up-to-date permission handler?

Thank you, sir :)

**Comment by zeeshux7860** [comment]
## Fixed Check image_editor_pro 1.0.6

first of all: Appreciate the time and effort you put into this plugin. Your description sounds like exactly what I am looking for, so thank you very much.

When trying to install though, I get the following error:

Because every version of image_editor_pro depends on permission_handler ^4.2.0+hotfix.3 and myApp depends on permission_handler ^5.0.0+hotfix.3, image_editor_pro is forbidden.

So, because myApp depends on image_editor_pro ^1.0.5, version solving failed.

Any chance you can fix this so that it can be used with up-to-date permission handler?

Thank you, sir :)


 Thanks you :)

**Comment by gisinator** [comment]
Awesome, wow, what a super fast service :)

**Comment by zeeshux7860** [comment]
yup yup :)
